version: 0.0
os: windows
files:
  - source: target/jb-hello-world-maven-0.1.0.jar
    destination: C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps
hooks:
   ApplicationStart:
    - location: scripts/start_server.bat
   ApplicationStop:
    - location: scripts/stop_server.bat
